name: Telegram Notification

on: 
  push:
    branches:
      - main
  pull_request:
    types: [opened, closed]

jobs:
  notify_telegram:
    runs-on: ubuntu-latest

    steps:
    - name: Send notification to Telegram
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        # Variables to format the message
        REPO_NAME="📂 *${GITHUB_REPOSITORY}*"  # Bold repository name with icon
        PUSHER_NAME="${{ github.actor }}"  # Person who pushed the changes
        PUSHER_LINK="https://github.com/${PUSHER_NAME}"  # Link to pusher's GitHub profile
        COMMIT_MESSAGE="💬 _${{ github.event.head_commit.message }}_"  # Italic commit message with icon
        BRANCH_NAME="🖇 Branch: \`${{ github.ref_name }}\`"  # Branch name with icon

        # Telegram API call to send a sticker (Optional)
        curl -s -X POST https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendSticker \
          -d chat_id=${TELEGRAM_CHAT_ID} \
          -d sticker="CAACAgIAAxkBAAED3d9kItBtdNkEjFWfpAfqZEDG5jM_jAACAwADwDZPE4nTUpUqOikvHgQ"  # Example sticker ID

        # Telegram API call to send the message with Markdown formatting
        curl -s -X POST https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage \
          -d chat_id=${TELEGRAM_CHAT_ID} \
          -d parse_mode="Markdown" \
          -d disable_web_page_preview=true \
          -d text="📝 *GitHubimdagi o'zgarishlar*%0A%0A${REPO_NAME}%0A👤 Pushed by: [${PUSHER_NAME}](${PUSHER_LINK})%0A${BRANCH_NAME}%0A${COMMIT_MESSAGE}"
